spring:
    data:
        mongodb:
            uri: mongodb+srv://saminamina:kkk123kkk@train.ciaxsoa.mongodb.net/?retryWrites=true&w=majority&appName=Train
            database: Train
    application:
        name: springboot-mongo-atlas